#!/bin/sh
set -eu
# Generate a random hex password with 20 bytes of entropy (corresponds to 40
# hex characters which is the most RDS will allow).
password=$(dd if=/dev/urandom bs=1 count=20 2>/dev/null | xxd -p -c 64)

# Store in SSM ParameterStore as an encrypted string.
aws ssm put-parameter \
    --region us-east-1 \
    --name db-master-password \
    --type SecureString \
    --value "$password"
